import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://deltadefenders-qa.elixirlab.net/web/tango');
  await page.getByRole('textbox', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Login' }).fill('');
  await page.getByRole('textbox', { name: 'Login' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.waitForTimeout(5000);
  //await page.goto('https://trunk-qa.elixirlab.net/elixir/default/dashboard');
 await page.locator('#settings-svg').click();
 await page.waitForTimeout(2000);
  await page.getByText('Workspace').click();
  await page.waitForTimeout(8000);
  await page.getByText('Strategy').click();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: 'Goals' }).click();
  await page.getByRole('button', { name: 'New' }).click();
  await page.getByRole('textbox', { name: 'Enter title' }).click();
  await page.getByRole('textbox', { name: 'Enter title' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter title' }).fill('A');
  await page.getByRole('textbox', { name: 'Enter title' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter title' }).fill('Auto_');
  await page.getByRole('textbox', { name: 'Enter title' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter title' }).fill('Auto_T');
  await page.getByRole('textbox', { name: 'Enter title' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter title' }).fill('Auto_Test');
  await page.getByRole('textbox', { name: 'Enter Success Metrics' }).click();
  await page.getByRole('textbox', { name: 'Enter Success Metrics' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter Success Metrics' }).fill('N');
  await page.getByRole('textbox', { name: 'Enter Success Metrics' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter Success Metrics' }).fill('New ');
  await page.getByRole('textbox', { name: 'Enter Success Metrics' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter Success Metrics' }).fill('New M');
  await page.getByRole('textbox', { name: 'Enter Success Metrics' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter Success Metrics' }).fill('New Metrics');
  await page.getByRole('textbox', { name: 'Enter description' }).click();
  await page.getByRole('textbox', { name: 'Enter description' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter description' }).fill('A');
  await page.getByRole('textbox', { name: 'Enter description' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter description' }).fill('Auto_');
  await page.getByRole('textbox', { name: 'Enter description' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter description' }).fill('Auto_D');
  await page.getByRole('textbox', { name: 'Enter description' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter description' }).fill('Auto_Description');
  await page.locator('input[name="color"]').click();
  await page.locator('.MuiBox-root.css-10dkpmn').click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByText('AS', { exact: true }).click();
  await page.getByText('Logout').click();
});